AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: s3 trigger test

Parameters:   
  S3BucketParameter:
    Type: String
    Default: s3-upload-bucket

Resources:
  
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketParameter
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  S3TriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      FunctionName: S3-EB-Lambda-Trigger-POC
      Runtime: dotnet6
      MemorySize: 128
      Timeout: 30
      CodeUri: 
      Handler: AWS.S3.Lambda.Trigger::AWS.S3.Lambda.Trigger.Function::FunctionHandler      
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectACL
                - s3:DeleteObject
                - s3:PutObject
                - s3:PutObjectAcl
              Resource:
                !Sub 'arn:aws:s3:::${S3BucketParameter}/*'
                    
  EventRule: 
    Type: AWS::Events::Rule
    Properties:
      Name: S3-EB-Lambda-Trigger-Rule
      Description: trigger lambda on object copy
      State: ENABLED
      EventPattern: 
        source: 
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name: 
              - !Ref S3BucketParameter
          object:
            key:
              - prefix: 'upload/files/'
              - prefix: 'upload/images/'
      Targets:
        - Arn: !GetAtt S3TriggerLambda.Arn
          Id: S3TriggerLambdaTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref S3TriggerLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn


Outputs:
  LambdaArn:
    Description: The ARN of the created Lambda function. This is used to create a trigger from S3
    Value: !GetAtt S3TriggerLambda.Arn


